{{- if eq (lower .Values.provider.name) "gke" }}
{{- $defaultValues := deepCopy .Values.inferenceExtension -}}
{{- $defaultName := $defaultValues.name | default (printf "%s-epp" .Release.Name) -}}
---
kind: HealthCheckPolicy
apiVersion: networking.gke.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-api-inference-extension.labels" . | nindent 4 }}
spec:
  targetRef:
    group: inference.networking.x-k8s.io
    kind: InferencePool
    name: {{ .Release.Name }}-standard
  default:
    # Set a more aggressive health check than the default 5s for faster switch
    # over during EPP rollout.
    timeoutSec: 2
    checkIntervalSec: 2
    {{- $port := .Values.inferencePool.targetPortNumber }}
    {{- if .Values.inferencePool.targetPorts }}
      {{- $port = (index .Values.inferencePool.targetPorts 0).number }}
    {{- end }}
    {{- if eq .Values.inferencePool.modelServerProtocol "http" }}
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /health
        port: {{ $port }}
    {{- else if and (eq (lower .Values.inferencePool.modelServerType) "vllm") (eq .Values.inferencePool.modelServerProtocol "grpc") }}
    config:
      type: GRPC
      grpcHealthCheck:
        portSpecification: "USE_FIXED_PORT"
        port: {{ $port }}
        grpcServiceName: "/vllm.grpc.engine.VllmEngine/HealthCheck"
    {{- end }}
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ .Release.Name }}-default
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ $defaultName }}
  default:
    timeoutSec: 300
    logging:
      enabled: true
    {{- if .Values.inferenceExtensionPreferred.enabled }}
    backendPreference: DEFAULT
    {{- end }}

---
{{- if .Values.inferenceExtensionPreferred.enabled }}
  {{- $preferredValues := deepCopy .Values.inferenceExtension -}}
  {{- if .Values.inferenceExtensionPreferred }}
    {{- $preferredValues = merge .Values.inferenceExtensionPreferred .Values.inferenceExtension -}}
  {{- end -}}
  {{- $preferredName := $preferredValues.name | default (printf "%s-epp-preferred" .Release.Name) -}}
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ .Release.Name }}-preferred
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ $preferredName }}
  default:
    timeoutSec: 300
    logging:
      enabled: true
    backendPreference: PREFERRED
{{- end }}
---
{{- end }}
{{- include "inference-extension.gke" . -}}
