apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "precise-prefix-cache-aware.fullname" . }}-config
  labels:
    {{- include "precise-prefix-cache-aware.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $config := .Values.config | deepCopy -}}
    {{- $secretToken := index (lookup "v1" "Secret" .Release.Namespace .Values.hfTokenSecret.name).data .Values.hfTokenSecret.key | b64dec -}}
    {{- $_ := set $config.tokenizer "token" $secretToken -}}
    {{- toYaml $config | nindent 4 }}