{{- if .Values.hfToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "precise-prefix-cache-aware.hfSecret" . }}
  labels:
    {{- include "precise-prefix-cache-aware.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.hfToken | b64enc }}
{{- end }}
